# Generated by Django 3.0.4 on 2020-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
